import { useEffect, useState, type ReactNode } from 'react';
import { ArrowUpRight, X, Inbox } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { initials } from '@/state/mock-data';

export function Avatar({name,size='md'}:{name:string;size?:'sm'|'md'|'lg'}) { return <span title={name} className={`inline-flex shrink-0 items-center justify-center rounded-full bg-peach font-semibold text-primary ${size==='sm'?'size-7 text-[10px]':size==='lg'?'size-16 text-lg':'size-9 text-xs'}`}>{initials(name)}</span> }
export function AvatarGroup({names}:{names:string[]}) { return <div className="flex items-center pl-1">{names.slice(0,4).map((n,i)=><span key={`${n}-${i}`} className="-ml-1.5 border-2 border-card rounded-full"><Avatar name={n} size="sm"/></span>)}{names.length>4&&<span className="-ml-1.5 flex size-7 items-center justify-center rounded-full border-2 border-card bg-muted text-[10px]">+{names.length-4}</span>}{!names.length&&<span className="text-xs text-muted-foreground">Unassigned</span>}</div> }
export function StatusBadge({children}:{children:ReactNode}) { const value=String(children); const tone=/completed|closed|confirmed|available|returned|accepted|active|repaired|good|arrived/i.test(value)?'success':/rejected|cancelled|damaged|lost|overdue|inactive/i.test(value)?'danger':/pending|follow-up|maintenance|leave|fair|awaiting/i.test(value)?'warning':/progress|assigned|contacted|discussion|quotation|way/i.test(value)?'info':'primary'; return <span className={`inline-flex max-w-full items-center gap-1.5 whitespace-nowrap rounded-full px-2.5 py-1 text-[11px] font-semibold badge-${tone}`}><span className="size-1.5 rounded-full bg-current"/>{children}</span> }
export function SectionHeading({eyebrow,title,action}:{eyebrow?:string;title:string;action?:ReactNode}) { return <div className="mb-5 flex flex-wrap items-end justify-between gap-3"><div>{eyebrow&&<p className="mb-1 text-[11px] font-semibold uppercase tracking-[.16em] text-primary">{eyebrow}</p>}<h2 className="display text-[23px] font-semibold text-foreground">{title}</h2></div>{action}</div> }
export function EmptyState({title,description,action}:{title:string;description:string;action?:ReactNode}) { return <div className="flex min-h-44 flex-col items-center justify-center px-4 py-8 text-center"><div className="mb-3 grid size-10 place-items-center rounded-xl bg-accent text-primary"><Inbox size={19}/></div><p className="font-semibold">{title}</p><p className="mt-1 max-w-56 text-xs leading-relaxed text-muted-foreground">{description}</p>{action&&<div className="mt-4">{action}</div>}</div> }
export function Metric({label,value,icon:Icon,note,highlight=false}:{label:string;value:number|string;icon:React.ComponentType<{size?:number;className?:string}>;note?:string;highlight?:boolean}) { const [shown,setShown]=useState(0); useEffect(()=>{ if(typeof value!=='number')return; let frame:number; const start=performance.now(); const tick=(now:number)=>{ const progress=Math.min((now-start)/1000,1);setShown(Math.round(value*(1-(1-progress)**2)));if(progress<1)frame=requestAnimationFrame(tick)};frame=requestAnimationFrame(tick);return()=>cancelAnimationFrame(frame)},[value]); return <div className={`surface relative overflow-hidden p-5 transition-transform duration-200 hover:-translate-y-0.5 ${highlight?'border-t-[3px] border-t-primary':''}`}><div className="flex items-start justify-between gap-2"><span className="text-xs font-medium text-muted-foreground">{label}</span><span className={`grid size-9 place-items-center rounded-lg ${highlight?'bg-accent text-primary':'bg-secondary text-foreground'}`}><Icon size={17}/></span></div><div className="mt-3 flex items-end justify-between"><span className="display text-[36px] leading-none font-semibold">{typeof value==='number'?shown:value}</span>{note&&<span className="flex items-center gap-0.5 text-[11px] font-medium text-success"><ArrowUpRight size={13}/>{note}</span>}</div></div> }
export function Overlay({title,children,onClose,wide=false,footer}:{title:string;children:ReactNode;onClose:()=>void;wide?:boolean;footer?:ReactNode}) { useEffect(()=>{const esc=(e:KeyboardEvent)=>{if(e.key==='Escape')onClose()};window.addEventListener('keydown',esc);return()=>window.removeEventListener('keydown',esc)},[onClose]); return <div className="fixed inset-0 z-50 flex justify-end bg-foreground/35" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><div role="dialog" aria-modal="true" aria-label={title} className={`flex h-full w-full flex-col bg-card shadow-2xl animate-in slide-in-from-right duration-300 ${wide?'max-w-[800px]':'max-w-[560px]'}`}><header className="flex shrink-0 items-center justify-between border-b px-6 py-5"><h2 className="display text-2xl font-semibold">{title}</h2><Button variant="ghost" size="icon" aria-label="Close panel" onClick={onClose}><X size={18}/></Button></header><div className="scrollbar-thin min-h-0 flex-1 overflow-y-auto p-6">{children}</div>{footer&&<footer className="flex flex-wrap justify-end gap-2 border-t bg-card px-6 py-4">{footer}</footer>}</div></div> }
